- newsletters/2018-03-15.md
Here is a first draft of the first newsletter styled after the old Impl period newsletters.
In the future we should have a list of projects to watch for updates :)
> First Newsletter

- README.md
As suggested by @japaric in #46.
> Add link to avr-rust organisation to README

- newsletters/2018-04-14.md
Closes https://github.com/rust-lang-nursery/embedded-wg/issues/72
Rendered: https://github.com/rust-lang-nursery/embedded-wg/blob/third-newsletter/newsletters/2018-04-14.md
> Third newsletter

- newsletters/2018-04-28.md
Fourth Newsletter
Closes #84
[Rendered Here](https://github.com/rust-lang-nursery/embedded-wg/blob/newsletter-4/newsletters/2018-04-28.md)
> Fourth Newsletter

- newsletters/2018-05-12-the-path-towards-stable.md
- newsletters/2018-05-13-the-path-towards-stable.md
this is an announcement I'm preparing and that I'll (hopefully) post later today on u.r-l.o (\*).
First, it announces that library development is possible on beta, then it explains what's missing to
make application development possible on stable. Then it covers the ongoing migration of the
Cortex-M ecosystem to stable on how you can help; in particular, it covers how to update device
crates, driver crates and HAL implementation crates. In ends by explaining what these changes mean
to current and future users; and what's the state of other architectures.
Any feedback is appreciated! cc @thejpster @jamesmunns @hannobraun @jcsoo @pftbest @dvc94ch
@dylanmckay
Note that several links are currently broken as I haven't finished publishing stuff but I'll fix
them all before posting the …
> add "the path towards stable" announcement

- README.md
Open question: Is this the correct link that we want?
Another possibility would be the raw GitHub link: https://github.com/rust-lang/rfcs
> Fix link to Rust RFC process in README

- ops/README.md
- ops/post-transfer.md
- ops/publish.md
- ops/review.md
As suggested in https://github.com/rust-embedded/wg/issues/148#issuecomment-411246711.
I'm putting them in a PR for now regardless of wherever we decide to put them in the end because that seems like a better place than in my head :-).
cc @jamesmunns @adamgreig
> add operational notes

- README.md
Syntax was a bit off so these were showing up as empty bullets.
> Fix links for embedded Linux team

- .github/CODEOWNERS
- README.md
he's already included in the list of owner as a member of the rust-embedded/all team
Forgot to add links to the usernames added in #174
r? @rust-embedded/all
> add links to README; remove thejpster from CODEOWNERS ..

- README.md
now we can link people to the README instead of answering these questions on IRC, reddit, e-mail and
the like.
r? @rust-embedded/all
> README: add what-we-do and how-you-can-help sections

- README.md
This a proposal to log our IRC channel using logbot.
This proposal (PR) needs at least 10 votes (approvals) from @rust-embedded/all
to be accepted. After the proposal has been accepted we'll proceed to implement
it.
@rust-embedded/all please vote on this proposal using [pull request reviews].
Or if you have a concern leave a comment.
[pull request reviews]: https://help.github.com/articles/about-pull-request-reviews/
closes #171
> use logbot to log our IRC channel

- newsletters/2018-08-2x-psa-cortex-m-breakage.md
This is the PSA we'll put up when the default linker of the Cortex-M targets
changes.
I'm putting it up for early review. It's OK to merge it before the breaking
change occurs.
r? @rust-embedded/resources
> PSA notice for upcoming Cortex-M breakage

- rfcs/0000-blog.md
This a proposal to create and maintain our own blog.
[Rendered version of this proposal](https://github.com/rust-embedded/wg/blob/blog/rfcs/0000-blog.md)
This proposal (PR) needs at least 10 votes (approvals) from @rust-embedded/all
to be accepted. After the proposal has been accepted we'll proceed to implement
it.
@rust-embedded/all please vote on this proposal using [pull request reviews].
Or if you have a concern leave a comment.
[pull request reviews]: https://help.github.com/articles/about-pull-request-reviews/
cc #148
> [RFC] blog.rust-embedded.org

- README.md
> Fix ithinuel's link

- ops/irc.md
Hi,
as discussed in issue #154, here's my proposal in a better form.
[Rendered](https://github.com/levex/rust-embedded-wg/blob/irc-op-notes/ops/irc.md)
There are a couple of questions I could think of:
* Is there any point in listing the rights associated with each access level?
* Should we have an IRC roster in the repo?
* Do we need more owners?
* Do we need voice (`+v`)?
Best wishes,
Levente
> IRC Operational Notes

- rfcs/0000-embedded-rust-showcase.md
Follow-up from #147 and today's IRC meeting.
[Rendered](https://github.com/rust-embedded/wg/blob/embedded-rust-showcase/rfcs/0000-embedded-rust-showcase.md)
cc @rust-embedded/resources
> [RFC] Embedded Rust Showcase

- minutes/2018-09-04.irc.log
- minutes/2018-09-04.md
r? @rust-embedded/all (anyone)
> add logs and minutes for last meeting

- README.md
This is a proposal for creating a Cortex-R team.
@paoloteti and I will be the initial members. I know pretty much nothing about
the Cortex-R but will be working with them starting November; @paoloteti is the
real expert here.
The following work has been planed for this team (some of it has been done
already)
rust-lang/rust#53679 we went from 1 target to 4. We now have good coverage of
Cortex R4(F) and R5(F) cores.
rust-lang/rust#53679.
require nightly. Also done in rust-lang/rust#53679.
a safe API to emit arch-specific instructions and to manipulate system
registers.
helps building a minimal `no_std` binary.
TI ship with their IDEs.
(\*) Initial work in this area: https://github.com/paoloteti/ti-hercules-bsp
@rust-embedded/all please vote on this proposal using [GitHub reviews][approve]. …
> [RFC] initial Cortex-R team

- README.md
this PR formalizes the ops team which pretty much have been just @nastevens
until recently but now they are being joined by @ryankurte.
@rust-embedded/all can you please approve (via GitHub reviews) this PR? We need
12 approvals to land this.
> initial ops team

- minutes/2018-09-11.irc.log
- minutes/2018-09-11.md
r? @rust-embedded/all (anyone)
> add logs and minutes for the last meeting

- README.md
This is a proposal for creating a Cortex-A team.
This is based on and will close issue #182. Please refrain from approving until I removed the [DRAFT] from the title and every proposed member has his points on the agenda.
@raw-bin, @wizofe and me will be the initial members.
The following work is planned for this team:
------------------
@raw-bin and @wizofe, kindly let me know your agenda points and I will edit them into this comment.
I understand your Redox work will most probably be a part of it, but I want to leave it to you guys to describe it.
Once we are set, I will remove the [DRAFT] and open this for members to approve.
@jamesmunns I tend to agree to your thought about having a microprocessor group. However, I think that cortex-a alone is such a complex architecture, it can …
> [RFC] Initial Cortex-A team

- README.md
The crate is currently hosted under the rust-osdev organization: https://github.com/rust-osdev/register-rs. Moving it to the WG was part of the recently accepted [RFC for a Cortex-A team](https://github.com/rust-embedded/wg/pull/207#issuecomment-427606754).
This PR follows the process outlined in https://github.com/rust-embedded/wg/blob/master/rfcs/0136-teams.md#adopting-projects.
cc @andre-richter @japaric
> Add register-rs to the project list of new Cortex-A team

- README.md
Moving it to the WG was part of the recently accepted [RFC for a Cortex-A team](https://github.com/rust-embedded/wg/pull/207#issuecomment-427606754).
It is currently hosted here: https://github.com/andre-richter/cortex-a
> Add cortex-a to the project list of the Cortex-A team

- README.md
Ambiguity between working group operations and `ops` / `operations` team was raised at the last meeting. This PR renames the `ops` team to the `infrastructure` team to remove that ambiguity, as suggested in https://github.com/rust-embedded/wg/issues/217#issuecomment-425669425.
> Rename ops team to infrastructure team

- README.md
Documentation was recently moved to docs.rust-embedded.org and the old
links on this page now result in 404 errors.
Fixes #250
> Update bookshelf URLs to new location

- README.md
Currently hosted at https://github.com/posborne/rust-gpio-cdev.  The repo would be migrated to rust-embedded/gpio-cdev.
[`gpio-cdev`](https://crates.io/crates/gpio-cdev) is a new crate for interacting with GPIOs in Linux using the character device API (the sysfs interface is now deprecated and will be going away in future kernels [2020]).  Differences from the old API are [covered in the project README](https://github.com/posborne/rust-gpio-cdev#sysfs-gpio-vs-gpio-character-device).  Now that the initial work for the crate is done and an initial version of this crate, I want to transfer ownership over to the working group.
I didn't see a documented process for this kind of transfer, so I'm winging it a bit and using the change to the team ownership as a review checkpoint for the overall …
> Transfer gpio-cdev repo ownership to embedded Linux team

- README.md
This a proposal to give each team an e-mail address. As discussed in the last
meeting we'll be using the `team-name@teams.rust-embedded.org` format for the
e-mail addresses.
This proposal (PR) needs at least 10 votes (approvals) from @rust-embedded/all
to be accepted. After the proposal has been accepted we'll proceed to implement
it.
@rust-embedded/all please vote on this proposal using [pull request reviews].
Or if you have a concern leave a comment.
[pull request reviews]: https://help.github.com/articles/about-pull-request-reviews/
> add e-mail addresses for the teams

- README.md
DCC (Debug Communication Channel) is a debug interface similar to Cortex-M's
ITM.
r? @rust-embedded/cortex-r
> add cortex-r, dcc and panic-dcc to crates maintained by the cortex-r team

- ops/highfive.md
This PR adds some notes about how to use highfive and a bit of how it works.
For now, highfive has been enabled for the cortex-m repository, but we can send
a PR to rust-lang-nursery/highfive to enable it on other rust-embedded repos.
There's one extra step, which I can do, after the PR lands
Questions:
- Do we want to use highfive on *all* the rust-embedded repos?
- Do we want to do that ^ in one sweep or incrementally? e.g. one team at a time
cc @rust-embedded/all
> notes on highfive

- README.md
As RFC #136 states we'll create a triage team to keep PRs moving. The linked RFC describes the job
of the triage team. If you are interested in being part of the triage team leave a comment below.
> Form the triage team

- ops/msrv.md
> MSRV policy

- README.md
As I mentioned in #328 I'll be busier and busier during the next few months so
I'll be temporarily removing myself from some teams. For the next few months
I'll limit my duties to /core, /cortex-r (can't have a one-person team!) and
/ecosystem (when it's formed).
cc @rust-embedded/cortex-m @rust-embedded/embedded-linux @rust-embedded/hal
@rust-embedded/tools
@rust-embedded/triage I will remove myself from the highfive rotation so don't
assign new PRs to me
(This doesn't need voting just notifying the affected teams and a single approval.)
> temporarily remove japaric from some teams

- minutes/2019-03-05.irc.log
- minutes/2019-03-05.md
Now both minutes and IRC logs [can be extracted automatically](https://github.com/Disasm/rust-ewg-meta/tree/master/scripts) (you need Dropbox API token for accessing Dropbox Paper).
> Add last meeting minutes and IRC logs

- README.md
This RFC proposes that we replace the position of the "lead" with a core team.
I (@japaric) will be busy working on my thesis for the next ~3 months and won't
be able to be as active in the WG as I have been. Instead of having a single
not so active lead for months I propose that we have a small core team that
takes over the functions of the lead.
The core team will inherit the functions of the lead, namely what's already in
the README:
- Representing the WG in meetings with other Rust teams / WG.
- Communicating the needs of the embedded Rust community to the Rust teams.
- Giving the casting vote on intra-WG decisions where no voting majority can be
achieved.
- Driving and moderating the weekly meetings.
Additionally, we'll:
- Add the members of the core team to the rust-embedded/core …
> [RFC] lead -> core team

- README.md
Let me know if the linux-embedded-hal should be removed from the embbeded linux team instead of the HAL team.
> Remove linux-embedded-hal duplicat team assignment.

- ops/hibernating.md
This PR proposes a process that lets members 'hibernate' themselves when busy /
absent with the goals of not having highfive assign PRs to them and reducing the
number of votes required to get voting majority.
> ops: hibernating

- README.md
I haven't been very active in the working group for a long while now, and I don't see this changing much going forward. For this reason, I'm putting myself into the hibernation state.
I'm not leaving the community though! I'm still involved in [nrf-rs](https://github.com/nrf-rs), [lpc-rs](https://github.com/lpc-rs), and my various other open source projects. I also intend to still keep up with many of the WG repositories, so the main difference is going to be that I'll no longer feel bad for not doing any actual work :-)
cc @rust-embedded/hal
> Add "Hibernating" section to README, add myself

- README.md
Hello, I'd like to join the Rust RISC-V team!
I have various activity around RISC-V and Rust the last year:
- Contributed peripheral descriptions to [k210-pac](https://github.com/riscv-rust/k210-pac), and UART serial for [k210-hal](https://github.com/riscv-rust/k210-hal/)
- Wrote some [embedded demos in Rust](https://github.com/laanwj/k210-sdk-stuff) for the Maix Go Board, porting part of the Kendryte C SDK to Rust on the way
- Contributed to [rvsim](https://github.com/stephank/rvsim), a RV32G simulator in Rust
- Created [rust-riscv-disasm](https://github.com/laanwj/rust-riscv-disasm), a RISC-V disassembler in Rust
My primary interest in RISC-V is as a secure future architecture for bitcoin things. However, I'm also interested in advancing the state of Rust on RISC-V in general. I'm …
> laanwj joining RISC-V team

- README.md
See also: https://github.com/rust-embedded/wg/pull/306, https://github.com/rust-embedded/riscv/pull/25
> Fix RISC-V team name

- README.md
under the tools team
rationale: this is a direct dependency of svd2rust and could use more maintainers
The tools team needs to approve this PR
> move svd-parser into the org

- README.md
It turns out, the link to the chat room is difficult to find for the new users. This PR makes it more visible.
> Increase Matrix room visibility

- README.md
For some reason, `https://matrix.to/#/#rust-embedded:matrix.org` link leads to the page with more client options.
> Increase the newsletter visibility, fix Matrix room link

- rfcs/0000-multi-core-soundness.md
Change how we model multi-core MCUs in the following ways:
* Stop using `Send` and `Sync` to model anything related to cross-core
interactions since those traits are unfit for the purpose.
* Declare that `Send` is not sufficient to transfer resources between cores,
since memory addresses can have different meanings on different cores.
* Mutexes based on critical sections become declared sound due to the above:
They can only turn `Send` data `Sync`, but neither allows cross-core
interactions anymore.
* Punt on how to deal with cross-core communication and data sharing for now,
and leave it to the ecosystem.
[Rendered](https://github.com/jonas-schievink/wg/blob/multi-core-soundness/rfcs/0000-multi-core-soundness.md)
[`bare-metal`]: https://github.com/rust-embedded/bare-metal
> Address Multi-Core Soundness by abolishing Send and Sync

- projects/in-progress/0440-dma-api-documentation.md
Proposed shepherding project to explore and document safe DMA APIs.
Feedback is welcome.
[Rendered](https://github.com/thalesfragoso/wg/blob/dma-project/projects/in-progress/0440-dma-api-documentation.md)
> [Project] Documentation of DMA APIs

- projects/in-progress/0443-test-msrv.md
As we discussed in the last meeting, I'm proposing a new project on making sure all our crates have a documented and tested MSRV. This would be an ideal project for newcomers to help out with, as the work to do is fairly well defined but has an immediately useful impact on our projects' stability.
[(rendered)](https://github.com/rust-embedded/wg/blob/project-msrv/projects/in-progress/0443-test-msrv.md)
For reference, here are the discussion points:
* Do we want to also include a MSRV badge in repository READMEs? See [rand](https://github.com/rust-random/rand) for an example.
* Do we want to update the WG policy to stable-2, i.e. [#427](https://github.com/rust-embedded/wg/issues/427)?
> Add project proposal for documenting and testing MSRV in all WG crates

- README.md
I have not been active in this teams for a long time, so I decided to remove myself to slightly improve voting process.
> Remove @Disasm from Tools and Triage teams

- rfcs/0415-revising-unproven.md
- rfcs/xxxx-revising-unproven.md
[Rendered](https://github.com/rust-embedded/wg/blob/revising-unproven/rfcs/0415-revising-unproven.md)
> [RFC] Changing the way we handle addition/changes to the traits

- README.md
The following implements the changes talked about in the private @rust-embedded/all chat.
The following members actively requested to be hibernated:
* awygle 
* danc86 
* dvc94ch
* dylanmckay 
* ithinuel 
* jcsoo
* parched 
* paoloteti
* pftbest 
* sekineh 
* v-thakkar 
The following members have not yet responded, and I will attempt to reach out to them to confirm whether they would like to be hibernated or not:
Additionally, I realized we had the following team membership inconsistencies:
* @mathk - was not on the /all list
(If you are on either of these lists, please see https://github.com/orgs/rust-embedded/teams/all/discussions/13 for context)
Please do not merge before End of Day on 2020-07-11, or until all members have responded to stay or leave.
I've also gone ahead and removed …
> Hibernation Update

- README.md
So, we don't generally have a process for changing of the guard for the core team, but I think this is a healthy time to blaze some trails!
Due to scheduling and availability issues around [Ferrous Systems](https://ferrous-systems.com)' work on [OxidizeConf](https://oxidizeconf.com/) and [Sealed Rust](https://ferrous-systems.com/blog/sealed-rust-the-pitch/), I see myself being more and more busy over the coming months. For this reason, I plan to step down from the Core team, but remain on the Resources team.
Because it is important to have three people on the core team (to avoid deadlocked decisions), I'd also like to simultaneously nominate @adamgreig to replace me. In general, I'll plan on stepping down once a replacement is approved by @rust-embedded/all, whoever it is, but I think …
> Step down from the core team and nominate adamgreig

- rfcs/0523-msrv-2020.md
This RFC is an alternative to #449, as discussed in this week's meeting ([logs](https://freenode.logbot.info/rust-embedded/20201110#c5777770)). It proposes essentially removing our MSRV policy; the new requirement would be "build on current stable Rust".
I would specifically like to solicit feedback from anyone who benefits from our current MSRV policy (generally old Rust versions, at the least no newer than stable-3, specifically documented and tested against, and updated infrequently). At the moment I'm only directly aware of one use-case for a custom target which requires a custom rustc/llvm build. It would be really useful to hear from people who for whatever reason need to use an older Rust version, and to understand a bit more about why they need that and how this change might …
> [RFC] Alternative new MSRV policy

- minutes/2020-12-15.md
https://github.com/rust-embedded/wg/pull/527 is still pending too.
> Add minutes for 2020-12-15

- README.md
I was approached by @ryankurte about joining the embedded linux team and I would be happy to.
So far I have contributed to `rust-i2cdev` and `linux-embedded-hal` adding support for transactional I2C among other smaller fixes. See:
- https://github.com/rust-embedded/rust-i2cdev/pull/51
- https://github.com/rust-embedded/linux-embedded-hal/pull/26
Other than that I guess everyone here knows me already.
Nevertheless, please feel free to raise any concerns.
> Add eldruin to embedded linux team

- README.md
Updates README.md with link to @hargoniX github profile.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Fix link to hargoniX in README.md

- README.md
While it's still a work in progress, the community at [rp-rs](https://github.com/rp-rs) has built usable Rust crates for the RP2040 microcontroller, which should be mentioned in the list of device specific communities.
> Mention support of RP2040 microcontrollers

- rfcs/0000-move-itm-crate.md
As discussed in [the Matrix chat (from 2021-11-31--2021-12-01)](https://matrix.to/#/!BHcierreUuwCMxVqOf:matrix.org/$OcmpjhKy4iOk_5uQyhUpfVDA5_MtnNc1PkHVUDodSc8?via=matrix.org&via=psion.agg.io&via=beeper.com) here is an RFC proposing the disown/move of the [`itm`](https://crates.io/crates/itm) crate and repo for continued development outside of the WG.
[Rendered RFC](https://github.com/tmplt/wg/blob/move-itm-crate/rfcs/0000-move-itm-crate.md)
> rfcs: add move_itm_crate

- rfcs/0590-new-cross-org.md
[Rendered](https://github.com/rust-embedded/wg/blob/cross-rfc/rfcs/0590-new-cross-org.md).
This RFC is for the attention of @rust-embedded/tools who currently maintain the `cross` crate.
cc https://github.com/rust-embedded/cross/issues/574
> RFC for moving cross to its own organisation

- README.md
I would like to
- Help with `embedded-hal` development. Getting the `1.0` release done, helping with async, reviewing...
- Adopt [`critical-section`](https://github.com/embassy-rs/critical-section) into the WG as the official cross-arch critical section abstraction. See https://github.com/rust-embedded/cortex-m/pull/433, also discussed in some WG meetings previously. (I guess HAL is the most fitting team for it?)
Thank you!
~ Dario Nieuwenhuis
> I would like to join the HAL team.

- README.md
cortex-a and register-rs are both deprecated; cortex-a was replaced by aarch64-cpu while register-rs is replaced by tock-registers (not part of the wg).
> Update cortex-a team crates: drop cortex-a and register-rs, add aarch64-cpu

- README.md
I missed the link in #686, sorry!
> Fix links to aarch64-cpu crate

- README.md
Requesting following the thread with @adamgreig at https://github.com/rust-embedded/aarch64-cpu/pull/14
> Add nchong-at-aws to Cortex-A wg

- README.md
This PR updates links to RISC-V projects, as they are now together on a single workspace. I also added `riscv-pac` and `riscv-semihosting` to the list.
> Update links to RISC-V projects

- rfcs/0000-discovery-book-triage-2.md
- rfcs/0770-discovery-book-triage.md
> discovery book triage rfc version 2

- README.md
I initially joined the tools team to maintain `cross`, which isn't in this org anymore and I am not really using the other tools. I mostly use `heapless`, `embedded-hal`, `critical-section` and the various embedded Linux crates these days, and it makes sense to maintain the crates I actually use.
> Leave tools team, join HAL, libs and embedded Linux teams.

- surveys/2024-08-survey.md
CC #782 
This follows the [requested format](https://github.com/rust-lang/surveys/blob/main/surveys/notes/reference.md) for submission.
Once we have reviewed and merged this PR, I will copy the survey "upstream" to submit it to the survey team.
These are primarily the questions I originally proposed:
* All questions are optional
* There are 13 questions total
* When there are multiple choice options naming projects, I've made them alphabetical for fairness
* All "other" options allow for free entry
We do want to make this as short as possible to make it easy for people to complete, so if people think we can reasonably cut items, then I am open to that! If there are more important questions to be asking, I am open to that as well!
If there are any multiple choice options that I missed, …
> 2024 Embedded Survey Review

- README.md
After some discussions with @adamgreig and @nchong-at-aws, also supported by @andre-richter.
See also https://github.com/rust-embedded/aarch64-cpu/issues/29 for more context.
Part of my comms with Nathan, for transparency:
- I'm a long time committer to aarch64-cpu crate, 
- I would like to set up an automated publishing pipeline, review some pending PR's and perhaps go through some changes that folks introduced in the independent forks.
- I use this crate myself all the time, it's part of my OSdev project.
> Add @berkus to cortex-a team

- README.md
I would be honored to join the Arm team; I would like to help with AArch64 Rust targets, among other things.
JP adds:
> add Bart Massey to Arm team

- README.md
Same mistake as https://github.com/rust-embedded/wg/pull/861
> Fix missing link in README
