- newsletters/2018-03-29.md
Add some words to make the newsletter read more clearly.
Thanks for all of the work in the embedded-wg! It's really exciting to see how far we've come, and all of the wonderful places we'll go!
> Grammar pass

- README.md
> add the awesome embedded Rust list to the list of community projects

- newsletters/2018-05-28.md
Rendered: https://github.com/rust-lang-nursery/embedded-wg/blob/newsletter-6/newsletters/2018-05-28.md
> Newsletter 6

- newsletters/2018-07-15.md
Closes #103.
[Rendered here](https://github.com/rust-lang-nursery/embedded-wg/blob/newsletter-7/newsletters/2018-07-15.md), I will plan on merging and posting around 22:00 Europe/Berlin time if there are no comments.
CC @japaric
> Add Newsletter 7

- newsletters/2018-07-29.md
Closes https://github.com/rust-lang-nursery/embedded-wg/issues/121
[rendered](https://github.com/rust-lang-nursery/embedded-wg/blob/newsletter-8/newsletters/2018-07-29.md)
> Eighth newsletter

- README.md
to reflect the new ownership
this commit also uncomments several projects that were commented by mistake
r? anyone in @rust-embedded/all
> update project URLs

- README.md
r? @rust-embedded/all
cc @rust-embedded/irr-2018
> README: add the IRR 2018 team

- minutes/2018-08-13.irc.log
- minutes/2018-08-13.md
> add minutes and IRC logs of the last meeting

- minutes/2018-08-21.irc.log
- minutes/2018-08-21.md
r? @rust-embedded/all (anyone)
note that I have enabled bors on this PR so you'll have to `bors r+` this after
approving the PR
> add logs and minutes for the last meeting

- README.md
I apply to these teams because that plus rust is all I like to do !
> Propose myself for the cortex-m & hal teams

- minutes/2018-08-28.irc.log
- minutes/2018-08-28.md
> add logs and minutes for last meeting

- README.md
r? @rust-embedded/all (anyone)
> README: point readers to the embedded Rust book and the bookshelf

- README.md
Hey all, I'd like to join the embedded hal team to help triage and work through the issue pile ^_^
> Joining the embedded hal team

- minutes/2018-10-30.irc.log
- minutes/2018-11-06.irc.log
- minutes/2018-11-06.md
last week I committed the IRC logs with today's date so I'm also renaming that
file in this PR.
> add last meeting minutes and logs

- README.md
I've been unofficially on the resources team for a while now but I'd like to make it official!
cc/ @korken89 and @ryankurte who I think are in similar positions.
r? @rust-embedded/resources
> Add myself to Resources team list

- README.md
Hi! I would like to join the RISC-V team to help developing Rust support for this awesome architecture.
> Joining the RISC-V team

- README.md
> add team risc-v e-mail address

- ops/nominate.md
r? @jamesmunns or @therealprof
> ops: describe the process of nominating issues

- minutes/2019-03-19.irc.log
- minutes/2019-03-19.md
- minutes/2019-03-26.irc.log
- minutes/2019-03-26.md
Minutes for 2019-03-19 meeting were reconstructed by hand, so they can be inaccurate.
> Add last and prelast meeting minutes and IRC logs

- minutes/2019-04-02.irc.log
- minutes/2019-04-02.md
> Added last minutes and IRC logs

- README.md
so i can help triage and move some of the outstanding PRs.
cc. @rust-embedded/embedded-linux
> Add myself to the linux embedded team

- rfcs/0000-chat-vote.md
- rfcs/0351-chat-vote.md
This is still a work in progress.
[Rendered](https://github.com/rust-embedded/wg/blob/chat-vote/rfcs/0000-chat-vote.md)
CC @therealprof
> [RFC] Vote for new chat platform

- minutes/2019-06-04.irc.log
- minutes/2019-06-04.md
> Added meeting minutes and IRC logs for 2019-06-04

- README.md
As discussed in today's meeting I'd like to apply for membership of the tools team. I'm interested in the ongoing svd2rust work especially and would be happy to help reviewing PRs there.
> Add myself to Tools team

- README.md
As discussed at the meeting 2019-07-23, I'd like to help with svd2rust and its review process.
r? @rust-embedded/tools
> Add myself to the Tools team

- README.md
As discussed with @adamgreig, I will help maintain `cross`.
> Add myself to the tools team.

- minutes/2019-10-29.md
> Add meeting notes for 2019-10-29 meeting

- minutes/2019-12-10.md
Disregard the bad branch name.
closes #403
> Add minutes

- projects/in-progress/0440-dma-api-documentation.md
> Add tracking issues for the DMA project

- minutes/2020-03-10-hal-team.md
so we have a canonical source, cc. @jamesmunns
> Added hal-team meeting minutes

- minutes/2020-05-05.md
- minutes/2020-05-19.md
- minutes/2020-05-26.md
@therealprof has the missing notes for 2020-05-12
> Add notes from may

- README.md
@therealprof approached be about this.
I would be glad to help with `embedded-hal` and anything else related.
> Add myself to the HAL team

- ops/post-transfer.md
> Add GHA setup instructions

- README.md
Hi all,
With renovating a house, having a large delivery in our company, maintaining RTIC and trying to push in some WG time I am realizing that the load is too large right now and has been for a while.
I'm planning to hibernate for 2-3 months while the last of the house work and the company calms down, and then I'll be back!
If there are discussions around the Mutex or DMA traits, ping me - I'll be available for that!
BR Emil
> Hibernate korken89

- README.md
This PR implements the documentation update discussed in #462
> Add well supported devices to readme

- README.md
> Document that `nb` is maintained by the HAL team

- .github/CODEOWNERS
Spamming all current WG members with approval requests should suffice 😅
> No need to spam the old guard

- README.md
I also sorted the list alphabetically.
> Add myself to resources team

- minutes/2020-08-18.md
> Fix link typo in 2020-08-18.md

- minutes/2020-08-25.md
> Add minutes for 2020-08-25 meeting

- ops/post-transfer.md
`experimental` by itself does nothing.
> Add `continue-on-error` to GHA config

- ops/msrv.md
- ops/post-transfer.md
This PR updates our MSRV policy in line with RFC #523.
> Update MSRV policy

- minutes/2021-03-30.md
> Add minutes for 2021-02-30

- ops/post-transfer.md
We could probably refine these a bit; this is a starting point and just includes the current cortex-m cron CI job. Feedback welcome!
> Add notes about scheduled CI jobs

- README.md
I'd like to come out of hibernation and rejoin the Cortex-M team. As I also have a StarFive/BeagleV I thought it might also be useful if I joined the RISC-V team.
> theJPster awakes

- minutes/2021-05-25.md
I remembered to add the IRC log link this time, now that it's in the template I'll update it each week.
> Add minutes for 2021-05-25

- README.md
Hi, I'd like to join the risc-v working group team!  I've created this pull request to add my name to the README.md for voting.  Thank you for the consideration.
Daniel
> Proposal for addition to the RISC-V WG team

- README.md
1. I'd like to come off the RISC-V team - the one alpha prototype RISC-V board I has been abandoned by the manufacturer and so I haven't really done much work on it.
2. I'd like to join the Tools team.
3. I'd like to add my 'work' account (@jonathanpallant) in addition to my personal account (@thejpster) so I can use whichever machine I have in front of me.
> Update JP's memberships

- rfcs/0589-move-itm-crate.md
Should probably have done this before merging, oh well.
> Move ITM RFC to correct file name

- README.md
As discussed in the rust-embedded meeting today; see [this comment](https://github.com/rust-embedded/cortex-m/pull/355#issuecomment-1052351035) for additional context.
> Add @newAM to the Cortex-M team

- README.md
> Move @andre-richter to hibernating

- README.md
CC [#56](https://github.com/rust-embedded/embedded-alloc/pull/56).
> Rename to embedded-alloc

- README.md
@dkhayes117 invited me to join the RISC-V working group and asked me to officially request membership with this PR. It would be my pleasure to join you!
> Request to join the RISC-V working group

- README.md
> Add meta-rust-bin projet to embedded linux team

- README.md
I'd like to join the RISC-V and HAL team, if you'd have me :).
> I would like to join the RISC-V and HAL team.

- README.md
I'm happy to help out if more people are needed!
> Add newAM to the libs team

- README.md
I haven't been active for quite a while as I don't have enough time to follow EWG activities. Please put me to hibernation.
> Hibernate @Disasm

- README.md
As mentioned in today's community meeting, I will be volunteering for the RISC-V and Triage teams. I've submitted a PR to the `rust-lang/team` repository adding my name, as well.
JP edit: upstream PR https://github.com/rust-lang/team/pull/1111
> Add @jessebraham to RISC-V and Triage teams

- README.md
@eldruin invited me to join the Linux team. I would love to and here I am.
> Add @sirhcel to Linux team

- README.md
Split out from https://github.com/rust-embedded/wg/pull/727.
> Join libs team.

- README.md
I'll be away and unable to contribute or perform reviews for the next ~6 months.  When I'm back, I'll re-evaluate and potentially come out of hibernation.
CC @rust-embedded/embedded-linux
> Hibernate @posborne

- README.md
I'd like to get started with touching up the discovery book, as well as other learning resources that are maintained by the resources team.
Pending approval from (IIUC):
> Add hdoordt to resources team

- README.md
Want to help with documentation.
> Add Bart Massey to Resources team

- README.md
I'd like to join the Arm team, to continue the work on the cortex-ar and cortex-r-rt crates.
Work will slow down now my demo is ready for EW2025, but I can work on them in the background. I usually won't be attending the weekly meetings due to time constraints.
> Add JP to Arm team.

- README.md
Hi :)
I already talked with @thejpster  about this. I'd like to volunteer for membership of the ARM team, to also help with maintaining the new Cortex-AR support.
> Volunteering for ARM team

- README.md
Joining back:
- @rust-embedded/arm 
- @rust-embedded/embedded-hal 
- @rust-embedded/tools
> Wake ithinuel from hibernation
